### ISSUE TITLE
assertEquals

### ISSUE THREAD

**Issue by Tomathy-dev** [amadoandre/summer-internship-exercise-2023#1]
Penso que quando fazemos assertEquals (Object expected, Object actual), estamos a comparar se o objeto (que neste caso é um array de int) tem a mesma localização na memória, isto é, se é exatamente o mesmo objeto. Quando testei pela primeira vez, e me deu erro, fui verificar e tinha exatamente o mesmo array (a ordem dos valores iguais). Eu tentei substituir por asserArrayEquals() e funcionou. Queria saber se algures me enganei ou nao 😅

**Comment by HugoLCSB** [comment]
Tive exatamente o mesmo problema e solução, estava na duvida se seria uma espécie de rasteira propositada ou não.

**Comment by amadoandre** [comment]
Teem toda a razão , ja ha um commit a corrigir.  Obrigado ;)
